enabled: true
production-mode: false
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: false
spectre:
  exp: true
  icons: true
custom_logo:
  user/themes/quark/images/logo/devops.png:
    name: devops.png
    type: image/png
    size: 36461
    path: user/themes/quark/images/logo/devops.png
